In [ ]:
# Library used: https://github.com/glassonion1/anonypy

In [ ]:
"""
This notebook k-anonymized tabular data based on Mondrian algorithm
"""

In [1]:
import anonypy
import pandas as pd

In [38]:
# Load custom made dataset
data = pd.read_csv("/home/ammar/Desktop/LMU/Data Security NLP/data/data_datasecurity.csv")
del data["Unnamed: 0"]
del data["IP_ADDRESS"]

In [39]:
data.shape

(809, 12)

In [43]:
data

,TITLE,ASSIGNMENT,RACE/ETHNICITY,AGE,YEARS_IN_SERVICE,DEGREE,CITY_RESIDENT?,AGENCY,FIRST_NAME,LAST_NAME,EMAIL,GENDER
0,POLICE OFFICER,ADULT/JUVENILE BOOKING,AFRICAN AMERICAN,42.0,7.0,HGH SCHOOL GRADUATE,YES,BPD,Nat,Bilsland,nbilsland1@fda.gov,FEMALE
1,POLICE OFFICER,ADULT/JUVENILE BOOKING,AFRICAN AMERICAN,51.0,15.0,B.A. OR B.S. COMPLETED & RECEIVED,NO,BPD,Myrlene,Antoniutti,mantoniutti4@smugmug.com,FEMALE
2,POLICE OFFICER,ADULT/JUVENILE BOOKING,AFRICAN AMERICAN,44.0,15.0,HGH SCHOOL GRADUATE,NO,BPD,Kellie,Runacres,krunacres5@unicef.org,FEMALE
3,POLICE OFFICER,ADULT/JUVENILE BOOKING,AFRICAN AMERICAN,41.0,19.0,1 YEAR COLLEGE OR LESS,NO,BPD,Naoma,Losemann,nlosemann6@umich.edu,FEMALE
4,POLICE OFFICER,ANALYTICAL INTELLIGENCE SEC,AFRICAN AMERICAN,41.0,18.0,2 YEARS COLLEGE; NO A. A.,NO,BPD,Cinda,Parlott,cparlotta@histats.com,FEMALE
...,...,...,...,...,...,...,...,...,...,...,...,...
804,POLICE OFFICER,HUMAN RESOURCES SEC,AFRICAN AMERICAN,42.0,15.0,B.A. OR B.S. COMPLETED & RECEIVED,NO,BPD,Rossie,Huie,rhuierh@columbia.edu,MALE
805,POLICE OFFICER,HUMAN RESOURCES SEC,WHITE,43.0,5.0,B.A. OR B.S. COMPLETED & RECEIVED,NO,BPD,Noah,Sisneros,nsisnerosrj@google.es,MALE
806,POLICE OFFICER,HUMAN RESOURCES SEC,WHITE,45.0,21.0,HGH SCHOOL GRADUATE,NO,BPD,Paxton,Malicki,pmalickirl@admin.ch,MALE
807,POLICE OFFICER,HUMAN RESOURCES SEC,AFRICAN AMERICAN,47.0,15.0,A.A. COMPLETED & RECEIVED,YES,BPD,Hobart,Eyckelberg,heyckelbergrn@addthis.com,MALE
808,POLICE OFFICER,HUMAN RESOURCES SEC,AFRICAN AMERICAN,46.0,22.0,HIGH SCHOOL GED / EQUIVALENCY,YES,BPD,Herbie,Ucchino,hucchinoro@sciencedaily.com,MALE

In [45]:
# keep only first letter for First name last name

In [46]:
data["FIRST_NAME"]= data["FIRST_NAME"].apply(lambda x: x[0])
data["LAST_NAME"]= data["FIRST_NAME"].apply(lambda x: x[0])

In [40]:
# Basic data description

In [41]:
data.unstack().groupby(level=0).nunique()

AGE                  45
AGENCY                1
ASSIGNMENT           67
CITY_RESIDENT?        2
DEGREE               12
EMAIL               809
FIRST_NAME          762
GENDER                2
LAST_NAME           804
RACE/ETHNICITY       10
TITLE                10
YEARS_IN_SERVICE     41
dtype: int64

In [6]:
list(data.columns)

['TITLE',
 'ASSIGNMENT',
 'RACE/ETHNICITY',
 'AGE',
 'YEARS_IN_SERVICE',
 'DEGREE',
 'CITY_RESIDENT?',
 'AGENCY',
 'FIRST_NAME',
 'LAST_NAME',
 'EMAIL',
 'GENDER',
 'IP_ADDRESS']

In [7]:
data.head()

,TITLE,ASSIGNMENT,RACE/ETHNICITY,AGE,YEARS_IN_SERVICE,DEGREE,CITY_RESIDENT?,AGENCY,FIRST_NAME,LAST_NAME,EMAIL,GENDER,IP_ADDRESS
0,POLICE OFFICER,ADULT/JUVENILE BOOKING,AFRICAN AMERICAN,42.0,7.0,HGH SCHOOL GRADUATE,YES,BPD,Nat,Bilsland,nbilsland1@fda.gov,FEMALE,61.238.184.75
1,POLICE OFFICER,ADULT/JUVENILE BOOKING,AFRICAN AMERICAN,51.0,15.0,B.A. OR B.S. COMPLETED & RECEIVED,NO,BPD,Myrlene,Antoniutti,mantoniutti4@smugmug.com,FEMALE,19.38.52.95
2,POLICE OFFICER,ADULT/JUVENILE BOOKING,AFRICAN AMERICAN,44.0,15.0,HGH SCHOOL GRADUATE,NO,BPD,Kellie,Runacres,krunacres5@unicef.org,FEMALE,98.182.132.18
3,POLICE OFFICER,ADULT/JUVENILE BOOKING,AFRICAN AMERICAN,41.0,19.0,1 YEAR COLLEGE OR LESS,NO,BPD,Naoma,Losemann,nlosemann6@umich.edu,FEMALE,80.0.24.91
4,POLICE OFFICER,ANALYTICAL INTELLIGENCE SEC,AFRICAN AMERICAN,41.0,18.0,2 YEARS COLLEGE; NO A. A.,NO,BPD,Cinda,Parlott,cparlotta@histats.com,FEMALE,195.64.119.229

In [51]:

columns = list(data.columns)
categorical = set(('TITLE', 'ASSIGNMENT','RACE/ETHNICITY','DEGREE','CITY_RESIDENT?','AGENCY',"FIRST_NAME","LAST_NAME",'GENDER'))

def main():
    df = pd.DataFrame(data=data, columns=columns)

    for name in categorical:
        df[name] = df[name].astype("category")

    feature_columns = ['TITLE', 'ASSIGNMENT','DEGREE','CITY_RESIDENT?','GENDER',"AGENCY",'GENDER']
    sensitive_columns =  ["AGE","YEARS_IN_SERVICE","RACE/ETHNICITY"]
    dirs = {}
    
    for i in range(3):
        ls=[]
        for sensitive_column in sensitive_columns:
            p = anonypy.Preserver(df, feature_columns, sensitive_column)
            rows = p.anonymize_k_anonymity(k=2+i)
            dfn = pd.DataFrame(rows)
            ls.append(dfn)
            print(dfn.shape)
        dirs[2+i] = ls
    return dirs

In [52]:
out = main()

(739, 8)
(724, 8)
(404, 8)
(721, 8)
(698, 8)
(323, 8)
(692, 8)
(667, 8)
(258, 8)

In [ ]:
# 2,3,4-anoymity based on each of "AGE","YEARS_IN_SERVICE","RACE/ETHNICITY"

In [53]:
# K = 2 for Age
out[2][0]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,AGE,count
0,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,39.0,3
1,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,38.0,1
2,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,43.0,1
3,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...",B.A. OR B.S. COMPLETED & RECEIVED,NO,FEMALE,BPD,39.0,1
4,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...",B.A. OR B.S. COMPLETED & RECEIVED,NO,FEMALE,BPD,51.0,1
...,...,...,...,...,...,...,...,...
734,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,28.0,2
735,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,35.0,1
736,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,36.0,1
737,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,36.0,1
738,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,40.0,1

In [54]:
# K = 3 for Age
out[2][1]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,YEARS_IN_SERVICE,count
0,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,7.0,1
1,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,10.0,1
2,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,17.0,1
3,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,16.0,1
4,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,20.0,1
...,...,...,...,...,...,...,...,...
719,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,9.0,1
720,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,11.0,1
721,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,15.0,1
722,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,14.0,1
723,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,15.0,1

In [55]:
# K = 4 for Age
out[2][2]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,RACE/ETHNICITY,count
0,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,AFRICAN AMERICAN,1
1,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,WHITE,2
2,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,WHITE,2
3,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...",B.A. OR B.S. COMPLETED & RECEIVED,NO,FEMALE,BPD,AFRICAN AMERICAN,1
4,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...",B.A. OR B.S. COMPLETED & RECEIVED,NO,FEMALE,BPD,WHITE,1
...,...,...,...,...,...,...,...,...
399,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,2
400,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,OTHER HISPANIC,1
401,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,4
402,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,5
403,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,2

In [56]:
# K = 2 for YEAR IN SERVICE
out[2][0]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,AGE,count
0,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,39.0,3
1,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,38.0,1
2,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,43.0,1
3,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...",B.A. OR B.S. COMPLETED & RECEIVED,NO,FEMALE,BPD,39.0,1
4,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...",B.A. OR B.S. COMPLETED & RECEIVED,NO,FEMALE,BPD,51.0,1
...,...,...,...,...,...,...,...,...
734,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,28.0,2
735,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,35.0,1
736,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,36.0,1
737,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,36.0,1
738,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,40.0,1

In [57]:
# K = 3 for YEAR IN SERVICE
out[2][1]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,YEARS_IN_SERVICE,count
0,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,7.0,1
1,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,10.0,1
2,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,17.0,1
3,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,16.0,1
4,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,20.0,1
...,...,...,...,...,...,...,...,...
719,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,9.0,1
720,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,11.0,1
721,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,15.0,1
722,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,14.0,1
723,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,15.0,1

In [58]:
# K = 4 for YEAR IN SERVICE
out[2][2]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,RACE/ETHNICITY,count
0,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,AFRICAN AMERICAN,1
1,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,WHITE,2
2,"POLICE LIEUTENANT EID,POLICE SERGEANT EID","DEPLOYMENT UNIT,EQUAL OPPORTUNITY & DIVERSITY SEC",B.A. OR B.S. COMPLETED & RECEIVED,NO,MALE,BPD,WHITE,2
3,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...",B.A. OR B.S. COMPLETED & RECEIVED,NO,FEMALE,BPD,AFRICAN AMERICAN,1
4,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...",B.A. OR B.S. COMPLETED & RECEIVED,NO,FEMALE,BPD,WHITE,1
...,...,...,...,...,...,...,...,...
399,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,2
400,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,OTHER HISPANIC,1
401,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,4
402,POLICE OFFICER,SOUTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,5
403,POLICE OFFICER,WESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,2

In [59]:
# K = 2 for RACE/ETHNICITY
out[3][0]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,AGE,count
0,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,39.0,1
1,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,42.0,2
2,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,43.0,1
3,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,51.0,1
4,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,39.0,3
...,...,...,...,...,...,...,...,...
716,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,34.0,1
717,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,27.0,1
718,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,35.0,1
719,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,36.0,1
720,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,40.0,1

In [60]:
# K = 3 for RACE/ETHNICITY
out[3][1]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,YEARS_IN_SERVICE,count
0,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,15.0,1
1,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,18.0,1
2,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,19.0,2
3,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,20.0,1
4,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,7.0,1
...,...,...,...,...,...,...,...,...
693,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,7.0,2
694,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,15.0,1
695,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,5.0,1
696,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,9.0,2
697,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,18.0,1

In [61]:
# K = 4 for RACE/ETHNICITY
out[3][2]

,TITLE,ASSIGNMENT,DEGREE,CITY_RESIDENT?,GENDER,AGENCY,RACE/ETHNICITY,count
0,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,AFRICAN AMERICAN,4
1,"POLICE LIEUTENANT EID,POLICE MAJOR/DIRECTOR","GENERAL ACCOUNTABILITY OFFICE,INFORMATION SERV...","2 YEARS COLLEGE; NO A. A.,1 YEAR COLLEGE OR LE...",NO,FEMALE,BPD,WHITE,1
2,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,AFRICAN AMERICAN,1
3,"POLICE COLONEL,POLICE SERGEANT EID","NORTHERN DISTRICT,NEIGHBORHOOD PATROL DIV,NORT...",B.A. OR B.S. COMPLETED & RECEIVED,"NO,YES",FEMALE,BPD,WHITE,2
4,"POLICE MAJOR/DIRECTOR,POLICE LIEUTENANT COLONEL","DEPUTY COMM/CRIME REDUCTION BUR,EASTERN DISTRI...","A.A. COMPLETED & RECEIVED,1 YEAR COLLEGE OR LESS",NO,MALE,BPD,WHITE,3
...,...,...,...,...,...,...,...,...
318,POLICE OFFICER,SOUTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,4
319,POLICE OFFICER,"WESTERN DISTRICT,SOUTHWESTERN DISTRICT",HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,7
320,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,2
321,POLICE OFFICER,NORTHERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,OTHER HISPANIC,1
322,POLICE OFFICER,NORTHWESTERN DISTRICT,HGH SCHOOL GRADUATE,NO,FEMALE,BPD,AFRICAN AMERICAN,4